[versions]
activity-compose = "1.8.2"
androidx-junit = "1.1.5"
coil-compose = "2.5.0"
core-ktx = "1.12.0"
espresso-core = "3.5.1"
junit = "4.13.2"
lifecycle-runtime-ktx = "2.6.2"
lifecycle-runtime-compose = "2.6.1"
compose-bom = "2023.10.01"
agp = "8.2.0"
kotlin = "1.9.10"
appcompat = "1.6.1"
material = "1.11.0"
orbital = "0.3.3"
splash = "1.0.1"
navigation-compose = "2.7.6"
material-icons-extended = "1.5.4"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui"}
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics"}
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview"}
androidx-compose-material3 = { module = "androidx.compose.material3:material3"}
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4"}
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling"}
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest"}
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
junit = { module = "junit:junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
orbital = { module = "com.github.skydoves:orbital", version.ref = "orbital" }
splash-api = { module = "androidx.core:core-splashscreen", version.ref = "splash"}
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }